import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {chromium} from 'playwright';

const base=process.env.TABSIGHT_URL||'http://127.0.0.1:8787';
const python='.venv/bin/python';const fixtureArgs=['-m','scripts.browser_fixture','create'];if(process.env.TABSIGHT_E2E_PROJECT)fixtureArgs.push(process.env.TABSIGHT_E2E_PROJECT);
let id;try{id=execFileSync(python,fixtureArgs,{encoding:'utf8'}).trim();}catch(e){if(e.status==null)console.error(e.message);process.exit(e.status||1);}
fs.mkdirSync('test-results',{recursive:true});const errors=[];const results=[];
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
const report=name=>{results.push(name);console.log('PASS',name);};
const project=async()=>{const r=await fetch(`${base}/api/projects/${id}`);return r.json();};
const write=async(action)=>{const done=page.waitForResponse(r=>r.url().includes(`/api/projects/${id}`)&&['PUT','POST'].includes(r.request().method()));await action();const r=await done;assert.equal(r.status(),200,await r.text());await page.getByText('로컬 저장됨',{exact:true}).waitFor();};
const waitScore=async()=>{await page.locator('.alpha-host svg').first().waitFor({state:'visible'});await page.waitForTimeout(250);};
const setTime=async value=>{await page.getByLabel('재생 위치',{exact:true}).evaluate((el,value)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,String(value));el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},value);await page.waitForTimeout(200);};
try{
 await page.goto(base);await page.getByRole('heading',{name:'좋아하는 연주를, 나의 악보로.'}).waitFor();await page.screenshot({path:'test-results/home.png',fullPage:true});report('홈 화면');
 await page.locator('.project-item').filter({hasText:'브라우저 검증용 복제'}).click();await waitScore();await page.waitForTimeout(2000);const original=await project();report('실제 AI 결과로 악보 렌더링');
 const scoreNote=page.locator('.alpha-host svg text[fill="#B1701D"]').first();await scoreNote.scrollIntoViewIfNeeded();const notePoint=await scoreNote.evaluate(el=>{const pt=el.ownerSVGElement.createSVGPoint();pt.x=+el.getAttribute('x')+3;pt.y=+el.getAttribute('y')-4;const screen=pt.matrixTransform(el.getScreenCTM());return {x:screen.x,y:screen.y};});await page.mouse.click(notePoint.x,notePoint.y);await page.getByLabel('음표 시작',{exact:true}).waitFor();const clickedTime=+(await page.getByLabel('음표 시작',{exact:true}).inputValue());assert(Math.abs((await page.locator('video').evaluate(v=>v.currentTime))-clickedTime)<.15);report('악보 음표 클릭으로 영상 탐색');
 await page.getByRole('button',{name:'재생',exact:true}).click();await page.waitForTimeout(1100);const playing=await page.locator('video').evaluate(v=>({time:v.currentTime,paused:v.paused}));assert(playing.time>.5&&!playing.paused);await page.getByRole('button',{name:'일시정지',exact:true}).click();await page.getByLabel('재생 속도').selectOption('0.5');assert.equal(await page.locator('video').evaluate(v=>v.playbackRate),.5);report('원본 재생·일시정지·배속');
 await setTime(10);await page.locator('.loop-mark').first().click();await setTime(12);await page.locator('.loop-mark').nth(1).click();await setTime(11.8);await page.getByRole('button',{name:'재생',exact:true}).click();await page.waitForTimeout(1000);const loopTime=await page.locator('video').evaluate(v=>v.currentTime);assert(loopTime>=10&&loopTime<11.5,`Loop at ${loopTime}`);await page.getByRole('button',{name:'일시정지',exact:true}).click();await page.getByRole('button',{name:'A–B 반복',exact:true}).click();report('A–B 반복');
 await page.getByRole('button',{name:'악보음',exact:true}).click();const beforeSynth=+(await page.getByLabel('재생 위치').inputValue());await page.getByRole('button',{name:'재생',exact:true}).click();await page.waitForTimeout(1400);const afterSynth=+(await page.getByLabel('재생 위치').inputValue());assert(afterSynth>beforeSynth+.3);assert(await page.locator('video').evaluate(v=>v.paused));await page.getByRole('button',{name:'일시정지',exact:true}).click();report('합성 악보음 재생');
 await page.locator('.review-note').filter({hasNotText:'타격'}).first().click();const originalFret=+(await page.getByLabel('음표 프렛',{exact:true}).inputValue());await page.getByLabel('음표 프렛',{exact:true}).fill(String(originalFret+1));await write(()=>page.getByRole('button',{name:'수정 저장 · 검토 완료',exact:true}).click());assert.equal((await project()).revision,original.revision+1);await write(()=>page.getByRole('button',{name:'실행 취소',exact:true}).click());assert.equal(+(await page.getByLabel('음표 프렛',{exact:true}).inputValue()),originalFret);await write(()=>page.getByRole('button',{name:'다시 실행',exact:true}).click());assert.equal(+(await page.getByLabel('음표 프렛',{exact:true}).inputValue()),originalFret+1);await write(()=>page.getByRole('button',{name:'실행 취소',exact:true}).click());report('음표 수정·자동 저장·실행 취소·다시 실행');
 await write(()=>page.getByRole('button',{name:'현재 위치에 음표 추가',exact:true}).click());assert.equal((await project()).notes.length,original.notes.length+1);await write(()=>page.getByRole('button',{name:'음표 삭제',exact:true}).click());assert.equal((await project()).notes.length,original.notes.length);report('음표 추가·삭제');
 await page.getByLabel('기본 카포').fill(String(original.capo+1));for(let i=0;i<6;i++)await page.getByLabel(`${6-i}번 줄 튜닝`,{exact:true}).selectOption(String(original.tuning[i]-1));await write(()=>page.getByRole('button',{name:'원음 유지하고 운지 다시 계산',exact:true}).click());assert.deepEqual(Object.fromEntries((await project()).notes.map(n=>[n.id,n.midi])),Object.fromEntries(original.notes.map(n=>[n.id,n.midi])));await write(()=>page.getByRole('button',{name:'실행 취소',exact:true}).click());assert.equal((await project()).capo,original.capo);report('튜닝·카포 보정 시 원음 유지');
 await page.getByLabel('마디 템포').fill('110');await write(()=>page.getByRole('button',{name:'마디 보정 저장',exact:true}).click());assert((await project()).bars.some(b=>b.tempo===110));await write(()=>page.getByRole('button',{name:'실행 취소',exact:true}).click());report('마디 템포 편집');
 await page.reload();await waitScore();assert.deepEqual(Object.fromEntries((await project()).notes.map(n=>[n.id,n])),Object.fromEntries(original.notes.map(n=>[n.id,n])));report('새로고침 후 편집 상태 보존');
 const both=page.getByRole('button',{name:'TAB + 오선보',exact:true});assert(await both.count(),'TAB + staff should be the default view');await both.click();await page.waitForTimeout(300);await page.getByRole('button',{name:'TAB',exact:true}).click();await page.waitForTimeout(300);assert(await both.count());report('오선보 전환');
 await page.locator('.download-menu summary').click();for(const [format,label] of [['gp5','Guitar Pro 5'],['gp','Guitar Pro 7+']]){const pending=page.waitForEvent('download');await page.getByRole('button',{name:new RegExp(label.replace('+','\\+'))}).click();const dl=await pending;const out=`test-results/export.${format}`;await dl.saveAs(out);assert(fs.statSync(out).size>1000);const parsed=JSON.parse(execFileSync('node',['scripts/score-bridge.mjs','inspect',out],{encoding:'utf8'}));assert(parsed.notes.length>100);report(`${format} 다운로드·독립 재읽기`);}
 await page.locator('.download-menu summary').click();await page.screenshot({path:'test-results/workspace.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.screenshot({path:'test-results/mobile.png',fullPage:true});report('모바일 레이아웃');
 // Deleting through the sidebar also disposes of the copy; the fixture only cleans up after failures.
 await page.setViewportSize({width:1440,height:1000});const row=page.locator('.project-row').filter({hasText:'브라우저 검증용 복제'});await row.hover();page.once('dialog',dialog=>dialog.accept());await row.getByRole('button',{name:'브라우저 검증용 복제 채보 삭제',exact:true}).click();await row.waitFor({state:'detached'});await page.getByRole('heading',{name:'좋아하는 연주를, 나의 악보로.'}).waitFor();assert.equal((await fetch(`${base}/api/projects/${id}`)).status,404);report('연습실 목록에서 채보 삭제');
 assert.deepEqual(errors,[]);report('브라우저 예외 없음');
 fs.writeFileSync('test-results/browser-report.json',JSON.stringify({passed:results,errors},null,2));
}catch(e){await page.screenshot({path:'test-results/failure.png',fullPage:true});console.error(await page.getByRole('alert').allTextContents());throw e;}finally{await browser.close();execFileSync(python,['-m','scripts.browser_fixture','delete',id]);}
